[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "1572f36c9ba3c67b7b387155ea499681c1119975"
os = "macos"

    [[Mongoose.download]]
    sha256 = "036eeaf03f5f52f4a680b3c6a21b5f30b5b6e39f5bfa5e4f433e43ade8a3464e"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.aarch64-apple-darwin.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "3c037703fd9ce898e0d7ca4799ba555833aaf59e"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "c5d66984cb940f86b47318f4f101e62000ff27c17b0300b4f95d34b48782521d"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.aarch64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "3e942add59468d563114e0d11d6c9eb7184ca197"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "42f661236390fb1c21cb7b161ee03fefedce78922e919e6c2c10a24e0e8a31af"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.aarch64-linux-musl.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "36dc9169bd88c4d906f719ff4e69be370f29d8bf"
os = "freebsd"

    [[Mongoose.download]]
    sha256 = "f788272a90373362eac433725278fb60d1749f009e23c2d7d598ce465ea62349"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.aarch64-unknown-freebsd.tar.gz"
[[Mongoose]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0886050f136a29e344180dcfc178b630c79480a8"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "b2e4a0c5000358407ec1fb48f7ae9ae2ca466b212e25667c33977b4ef9295262"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.armv6l-linux-gnueabihf.tar.gz"
[[Mongoose]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f080cc9bc8d02ae6fe9a1bbb611a7bf15889824"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "367966f1a69de92eb8ea9da32d71ac78f5d633681d0c92c56f849cbe76e45430"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.armv6l-linux-musleabihf.tar.gz"
[[Mongoose]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "64e51f2b69cbedb52630d86bc916a18fa35a61f5"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "f941b77a30c5658d179e1c721d0690a8fbe024bcadcc7e75f4d157f0404c28e0"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.armv7l-linux-gnueabihf.tar.gz"
[[Mongoose]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "66cfc65710fe1a6ae57df5207e649444ebbba7d7"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "e2e9fd8c98f17ca1adfd97f816c70ac8596cef6ed7e260617c9e3828d956f36e"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.armv7l-linux-musleabihf.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "f39edee66eb64d964753e47afc21f1d63af136b7"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "0ac06e1dac4253aa6c75d08fb9e2d65391a5a534e8c68910102da64b59e22a52"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.i686-linux-gnu.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "b74db861e3de90cb2c6a4fcaba7c22fd5695bde3"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "44adf1c5347e2a8aa82a9d8085353ab104613bb4e7e877bb9a39dbfc217fcecf"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.i686-linux-musl.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "9389f63176c7a0f5040483878b7a08f4a7d8ac09"
os = "windows"

    [[Mongoose.download]]
    sha256 = "df2fdc9ae033175cb9703a158036c7854ebe8bd1a3f58be265d158a61d728938"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.i686-w64-mingw32.tar.gz"
[[Mongoose]]
arch = "powerpc64le"
git-tree-sha1 = "b261f113a47037bf203ae49b41260035b99e30e8"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "c9d96831f5eb7858dde3a16e11667d305117fc31ab478e74c1416ca5d8093d23"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.powerpc64le-linux-gnu.tar.gz"
[[Mongoose]]
arch = "riscv64"
git-tree-sha1 = "e7fe145fc550d4ebfa3187c687d87736960b49e7"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "dc029b4bad57651aaf4617007cf5a9be9cd7c3750d539cea4a80f8e86a82a246"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.riscv64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "f0ceb5ba2d128727e5676628caddea35b415093b"
os = "macos"

    [[Mongoose.download]]
    sha256 = "f5e57df4ad39c5d1fcf65d266bc5cdace7d758e82629fbe1786bd9e5ef9c608c"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.x86_64-apple-darwin.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "ed572bb58e58034ee0a7ed48dbf810e40f6e771d"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "babe01be6ff698147c154984d2dfdc833dc756657cc33ceb7009f87a0cd9abd4"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.x86_64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "cf8146f7c7b8c1f22320948823572d00034d86d1"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "ae9ce0afa8a7aa987ec0a05257e45a93324089c042780b53450d8602a2b4f1a2"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.x86_64-linux-musl.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "ac103b70277fa10cb63c1cfa6ccd53f277f3a089"
os = "freebsd"

    [[Mongoose.download]]
    sha256 = "cd95f5b90c9b42cdf570790c7ed44de59fe628bf41c291c8557ebb2a8e346823"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.x86_64-unknown-freebsd.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "2be0ec752b0ed98224e98d340f0cf0c2e5ed1115"
os = "windows"

    [[Mongoose.download]]
    sha256 = "c702e32143c63cc4276fb03fdd7c0c12d16355ffe6684f57913385b97d63eb4a"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.1+0/Mongoose.v7.23.1.x86_64-w64-mingw32.tar.gz"
