[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "b5bb0ebf3f28a6079889cf88ccfeadbe25be845a"
os = "macos"

    [[Mongoose.download]]
    sha256 = "500b1a8edc7db300b3d7da091ac9b90527227517bdb6fa07b82598eb36c3bb37"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.aarch64-apple-darwin.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "c23a0e359aa51504b6bd0b6d9fd0dbd4ac51a39a"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "44a20518e401ea1456cea309f11f3a1ed8dfe1c2e0fa6192edb45d190c5a6afc"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.aarch64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "6715dcb80a436f209902c83f60c7eec6162b5f1d"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "9275942ea6a4715abf8a78eab7c10caace8d858dc53916ce41f933ffb4841e33"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.aarch64-linux-musl.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "6b1d63adcc7a0608d5e7400702939cc2834ca192"
os = "freebsd"

    [[Mongoose.download]]
    sha256 = "5883e62ebcb708ffe64f75005e9b968549bba5fd7b6a3d33cf3afc2cec344fba"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.aarch64-unknown-freebsd.tar.gz"
[[Mongoose]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "80fb56429cb4a8011d2c5d292b8fcc658ba106b5"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "a552efd81e6afee51df5830819dabd88d7c56b6ebb306e7254e186baf092a847"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.armv6l-linux-gnueabihf.tar.gz"
[[Mongoose]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6c619503fe3f5056805c5b8d24f9bddcc5487ac8"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "dc6f8e68b508e4e869a7610861548aea6537b53bcd9d6e3f290aa9b1c7365044"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.armv6l-linux-musleabihf.tar.gz"
[[Mongoose]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9fb7098d42ae4670543dfb3cfa2c6c0b4b4772ec"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "cd12f3b0bfb91d02fcc742579cb53b024d0754a4ef99fada6b9d556882342843"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.armv7l-linux-gnueabihf.tar.gz"
[[Mongoose]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "13d7dc326d0aa34ffe602831361a49c711e17daa"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "b35d39fca1755dce8c1ac13853fc8351ea886ebd46b4d4e12960ca89790689a7"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.armv7l-linux-musleabihf.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "123bb6a494b8f992a03af65cecfc0e75151677df"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "4b58634ffecfcc6bb2746b8c37cd1cbbfbff89affa46fe9113793484ceda7391"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.i686-linux-gnu.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "92fcbae507297df073058150b3486a335d4ac018"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "93d6b0e6efe6339a232296eee0ed78faa3bef4ab6c7913f89e3460de3eaeae02"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.i686-linux-musl.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "fbf611d4321eb2065f689aae486e5632fb44d4a0"
os = "windows"

    [[Mongoose.download]]
    sha256 = "29ad12f5611d35b19cabafcffef1a68645f8636313bf921d2cde406134ef6302"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.i686-w64-mingw32.tar.gz"
[[Mongoose]]
arch = "powerpc64le"
git-tree-sha1 = "e52839c14dfdbf4545736786976994cbf83e5ecc"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "25aaaf7df8d75e37113db67f28ecd035d6aa23f74bb0f7ad512ab7174a258456"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.powerpc64le-linux-gnu.tar.gz"
[[Mongoose]]
arch = "riscv64"
git-tree-sha1 = "04175418cf7d0de06a36dc5fb1465857b7d8c339"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "aed7954aa6497401ae2c927dcf045fbfebe71cd7d82ed0ea5f5dcf3c91403c99"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.riscv64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "277798f6e23de5aaf72f7b07438ebf932e90dff4"
os = "macos"

    [[Mongoose.download]]
    sha256 = "1fa9972a6715ea3ade735d854d3644a7036fbdf35088a6e030029e29a87cca6e"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.x86_64-apple-darwin.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "5ed21c83d823f7035568c123211cc5701ae6497e"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "fb7f5c7bb8e39e43eeb5b88ef623c85ca36c339a00b8eae18a2060d642e834f8"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.x86_64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "7d227488932bbd6ea180af651bfe21f37a102355"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "1d8d0fbb684a54855fb0a8ce4ecf8efe09c16e86ecdbefecc4e024c557fa6e00"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.x86_64-linux-musl.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "9527766a9b2923e3278a5395c5e9d3c88bac56d3"
os = "freebsd"

    [[Mongoose.download]]
    sha256 = "d078b758169f23069ab77c6213da5e5a2e1234738b9a7bf7f9fc82afa3aacff8"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.x86_64-unknown-freebsd.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "2c94b9c066d0f07e186864cbc50dbb728b565729"
os = "windows"

    [[Mongoose.download]]
    sha256 = "4c522324e894902f9e1768bcc29bb3a1ac9ea77556ddc5627bc30b93dd1b49e2"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.23.0+0/Mongoose.v7.23.0.x86_64-w64-mingw32.tar.gz"
