# Autogenerated wrapper script for Mongoose_jll for aarch64-apple-darwin
export libmongoose

JLLWrappers.@generate_wrapper_header("Mongoose")
JLLWrappers.@declare_library_product(libmongoose, "@rpath/libmongoose.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmongoose,
        "lib/libmongoose.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
