# Autogenerated wrapper script for Mongoose_jll for armv6l-linux-musleabihf
export libmongoose

JLLWrappers.@generate_wrapper_header("Mongoose")
JLLWrappers.@declare_library_product(libmongoose, "libmongoose.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmongoose,
        "lib/libmongoose.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
