# Autogenerated wrapper script for Mongoose_jll for i686-w64-mingw32
export libmongoose

JLLWrappers.@generate_wrapper_header("Mongoose")
JLLWrappers.@declare_library_product(libmongoose, "libmongoose.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmongoose,
        "bin\\libmongoose.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
